### ISSUE TITLE
CFP: template texts

### ISSUE THREAD

**Issue by DrackThor** [cloud-native-austria/kcd-austria#26]
We need texts for the following stages of the CFP:

```[tasklist]
### Tasks
- [x] 'application submitted' text
- [x] 'application enters wainting list' text
- [x] 'application declined' text
- [x] 'application approved' text
- [x] we need a cfp email address
```

#14

**Comment by DrackThor** [comment]
My proposal for CfP email texts - please review, comment, improve!

## submitted session text:

Hello <name>!
Your session "<talk name>" has been successfully submitted - Thanks.
We'll keep you up to date about the state of your submitted session.

Best Regards,
KCD Austria Organizer Team

## session enters waiting list text:

Hello <name>!
Your session "<talk name>" has been added to the waiting list.
This means your session was not among the list of finally accepted applications.
However, if a planned session is cancelled and a place becomes free as a result, there is a chance to move up.
We'll keep you up to date about the state of your submitted session.

Best Regards,
KCD Austria Organizer Team

## session declined text:

Hello <name>!
Unfortunately, your session "<talk name>" has not been accepted for KCD Austria 2023.
Still, thank you for applying and we would love to hear from you next year.

Best Regards,
KCD Austria Organizer Team

## session accepted text:

Hello <name>!
Congratulations, your session "<talk name>" has been accepted for KCD Austria 2023.
We will get back at you with further information shortly.

Best Regards,
KCD Austria Organizer Team
