### ISSUE TITLE
Conference Pre-Flight

### ISSUE THREAD

**Issue by DavidPHirsch** [cloud-native-austria/kcd-austria#38]
```[tasklist]
### Tasks
- [ ] Check Conference Setup (in Rooms)
- [ ] Receive drinks
- [ ] Prepare sponsor area
- [ ] Prepare networking area
- [ ] Check and prepare speaker Wi-Fi
- [ ] Define contacts in case of problems
- [ ] Check electricity in sponsorship area
```
