### ISSUE TITLE
Create design for KCD Austria Stickers

### ISSUE THREAD

**Issue by thschue** [cloud-native-austria/kcd-austria#51]
```[tasklist]
### Tasks
- [ ] Create one version with year
- [ ] Create one version without year
- [ ] Submit the designs to Stickermule
```

**Comment by thschue** [comment]
First try without year: 
![image](https://github.com/cloud-native-austria/kcd-austria/assets/38893055/34a0867f-cb5b-44c4-a4f3-ebc5ba013071)
