### ISSUE TITLE
Checklist for event

### ISSUE THREAD

**Issue by DavidPHirsch** [cloud-native-austria/kcd-austria#6]
Hi Everyone,
creating a checklist based on the information given by the CNCF.

- [x] Verify that no other Kubernetes Community Day events are planned in your local area
- [x] Have a minimum of 3 local organizers (5 is recommended) from at least 3 different organizations. Each organizer needs to live in or just outside the KCD location.
- [x] Confirm that one of the organizer’s employers will agree to serve as a fiscal sponsor OR ask CNCF for help finding a fiscal sponsor.
- [x] Have a minimum of 3 sponsors. NOTE: It is not required to secure 3 sponsors ahead of launching your CFP.
- [x] Make sure that at least one organizer is an employee of a CNCF [member](https://www.cncf.io/about/members/), an [Ambassador](https://www.cncf.io/people/ambassadors/), or a CNCF project [maintainer](http://maintainers.cncf.io/)
- [x] Have a method to accept payments (sponsorships, tickets) and make payments (catering, A/V, other costs)
- [x] Verify that all organizers have agreed to these event guidelines and to abide by the CNCF [Code of Conduct](https://www.cncf.io/conduct/)
- [x] Schedule an event date a minimum of 6 months after you file your event request with CNCF request submission, (9 months prior is preferable)
- [x] Agree to use [Cloud Native Community Groups](https://community.cncf.io/) for [registration and ticketing](https://help.bevylabs.com/article/369-manage-event-ticketing)
- [x] Agree to use [Cloud Native Community Groups](https://community.cncf.io/) for organizing the program page
- [x] Agree to use [SM Apply](https://apply.surveymonkey.com/) for the CFP
- [x] Share CNCF Slack usernames for all organizers to be added to #KCD-organizers channel
- [x] Create a LinkedIn page or Twitter handle for specific KCD event (like @KCD-BouvetIsland) 
- [x] Create a Logo in SVG format(The logo is not permitted to include the Kubernetes Wheel (in whole or in part). The event logo must include the event name.)
- [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
- [x] Agree to offer at least 3 complimentary tickets to increase diversity for the event
- [x] Agree to share the sponsor prospectus with CNCF by linking it in your GitHub issue and on your website.
- [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, culture or company). [Here is how you can create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
- [x] Agree to submit your final lineup to [kcd@cncf.io](mailto:kcd@cncf.io) for review, prior to publishing it
