### ISSUE TITLE
Design On-Site Registration Process

### ISSUE THREAD

**Issue by thschue** [cloud-native-austria/kcd-austria#60]
```[tasklist]
### Tasks
- [ ] Define how badges will look like (content) and how they are created
- [ ] Check people for the entrance
- [ ] Check confirmation process
- [ ] Clarify opening time
- [ ] Add signs to find the conference
- [ ] Check goodie bag handout
```
